//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Mvc.Invest.Fideros.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSubscriptionForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSubscriptionForm() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Mvc.Invest.Fideros.Resources.ResourceSubscriptionForm", typeof(ResourceSubscriptionForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez accepter les conditions d&apos;utilisation.
        /// </summary>
        public static string accept_conditions_error_message {
            get {
                return ResourceManager.GetString("accept_conditions_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Conditions d&apos;utilisation.
        /// </summary>
        public static string accept_conditions_label {
            get {
                return ResourceManager.GetString("accept_conditions_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité obligatoire.
        /// </summary>
        public static string activity_code_error_message {
            get {
                return ResourceManager.GetString("activity_code_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        public static string activity_code_label {
            get {
                return ResourceManager.GetString("activity_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        public static string activity_label {
            get {
                return ResourceManager.GetString("activity_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur d&apos;activité obligatoire.
        /// </summary>
        public static string activityArea_error_message {
            get {
                return ResourceManager.GetString("activityArea_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité obligatoire.
        /// </summary>
        public static string activitydescription_error_message {
            get {
                return ResourceManager.GetString("activitydescription_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description Activité.
        /// </summary>
        public static string activitydescription_label {
            get {
                return ResourceManager.GetString("activitydescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Adresse&apos;.
        /// </summary>
        public static string address_line1_error_message {
            get {
                return ResourceManager.GetString("address_line1_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string address_line1_label {
            get {
                return ResourceManager.GetString("address_line1_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compl adr.
        /// </summary>
        public static string address_line2_label {
            get {
                return ResourceManager.GetString("address_line2_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Code Postal&apos;.
        /// </summary>
        public static string address_postal_code_error_message {
            get {
                return ResourceManager.GetString("address_postal_code_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Code postal.
        /// </summary>
        public static string address_postal_code_label {
            get {
                return ResourceManager.GetString("address_postal_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le nom agent d&apos;alerte.
        /// </summary>
        public static string alertName_error_message {
            get {
                return ResourceManager.GetString("alertName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom agent alert.
        /// </summary>
        public static string alertName_label {
            get {
                return ResourceManager.GetString("alertName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attachez fichier.
        /// </summary>
        public static string attachedFile_label {
            get {
                return ResourceManager.GetString("attachedFile_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thématique du blog obligatoire !.
        /// </summary>
        public static string BlogCatalogName_error_message {
            get {
                return ResourceManager.GetString("BlogCatalogName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thématique du blog.
        /// </summary>
        public static string BlogCatalogName_label {
            get {
                return ResourceManager.GetString("BlogCatalogName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Description&apos;.
        /// </summary>
        public static string BlogitemDescription_error_message {
            get {
                return ResourceManager.GetString("BlogitemDescription_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string BlogitemDescription_label {
            get {
                return ResourceManager.GetString("BlogitemDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Titre&apos;.
        /// </summary>
        public static string BlogitemName_error_message {
            get {
                return ResourceManager.GetString("BlogitemName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre.
        /// </summary>
        public static string BlogitemName_label {
            get {
                return ResourceManager.GetString("BlogitemName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous-thématique obligatoire !.
        /// </summary>
        public static string BlogSubCatalogName_error_message {
            get {
                return ResourceManager.GetString("BlogSubCatalogName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous-thématique.
        /// </summary>
        public static string BlogSubCatalogName_label {
            get {
                return ResourceManager.GetString("BlogSubCatalogName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salaire souhaité.
        /// </summary>
        public static string candidateSalary_label {
            get {
                return ResourceManager.GetString("candidateSalary_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Caractères re-saisis incorrects. Reessayez !.
        /// </summary>
        public static string captcha_error_message {
            get {
                return ResourceManager.GetString("captcha_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez re-saisir les caractères affichés.
        /// </summary>
        public static string captcha_label {
            get {
                return ResourceManager.GetString("captcha_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description obligatoire !.
        /// </summary>
        public static string CatalogDescription_error_message {
            get {
                return ResourceManager.GetString("CatalogDescription_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie obligatoire !.
        /// </summary>
        public static string CatalogName_error_message {
            get {
                return ResourceManager.GetString("CatalogName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catégorie.
        /// </summary>
        public static string CatalogName_label {
            get {
                return ResourceManager.GetString("CatalogName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référence offre à rappeler.
        /// </summary>
        public static string clientOfferRef_label {
            get {
                return ResourceManager.GetString("clientOfferRef_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fédération.
        /// </summary>
        public static string company_holding_name_label {
            get {
                return ResourceManager.GetString("company_holding_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forme leg..
        /// </summary>
        public static string company_legal_form_label {
            get {
                return ResourceManager.GetString("company_legal_form_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organisation obligatoire.
        /// </summary>
        public static string company_name_error_message {
            get {
                return ResourceManager.GetString("company_name_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Organisation.
        /// </summary>
        public static string company_name_label {
            get {
                return ResourceManager.GetString("company_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Siret.
        /// </summary>
        public static string company_register_number_label {
            get {
                return ResourceManager.GetString("company_register_number_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type organisation.
        /// </summary>
        public static string company_type_label {
            get {
                return ResourceManager.GetString("company_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation de mot de passe incorrecte.
        /// </summary>
        public static string confirm_password_compare_message {
            get {
                return ResourceManager.GetString("confirm_password_compare_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez confirmer le mot de passe.
        /// </summary>
        public static string confirm_password_error_message {
            get {
                return ResourceManager.GetString("confirm_password_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer mot de passe.
        /// </summary>
        public static string confirm_password_label {
            get {
                return ResourceManager.GetString("confirm_password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact obligatoire !.
        /// </summary>
        public static string contact_error_message {
            get {
                return ResourceManager.GetString("contact_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string contact_preference_label {
            get {
                return ResourceManager.GetString("contact_preference_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays de résidence .
        /// </summary>
        public static string country_label {
            get {
                return ResourceManager.GetString("country_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez choisir &apos;Pays&apos; .
        /// </summary>
        public static string CountryCodeItem_error_message {
            get {
                return ResourceManager.GetString("CountryCodeItem_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays.
        /// </summary>
        public static string CountryCodeItem_label {
            get {
                return ResourceManager.GetString("CountryCodeItem_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez choisir le Pays.
        /// </summary>
        public static string countryOffer_error_message {
            get {
                return ResourceManager.GetString("countryOffer_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pays.
        /// </summary>
        public static string countryOffer_label {
            get {
                return ResourceManager.GetString("countryOffer_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publié CV?.
        /// </summary>
        public static string cvDisplay_label {
            get {
                return ResourceManager.GetString("cvDisplay_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CV en PJ.
        /// </summary>
        public static string cvfile_label {
            get {
                return ResourceManager.GetString("cvfile_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début.
        /// </summary>
        public static string DateDebut_label {
            get {
                return ResourceManager.GetString("DateDebut_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date fin.
        /// </summary>
        public static string DateFin_label {
            get {
                return ResourceManager.GetString("DateFin_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le mois.
        /// </summary>
        public static string DateM_error_message {
            get {
                return ResourceManager.GetString("DateM_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date  naiss. obligatoire.
        /// </summary>
        public static string dateofbirth_error_message {
            get {
                return ResourceManager.GetString("dateofbirth_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date  naiss..
        /// </summary>
        public static string dateofbirth_label {
            get {
                return ResourceManager.GetString("dateofbirth_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir l&apos;année.
        /// </summary>
        public static string DateY_error_message {
            get {
                return ResourceManager.GetString("DateY_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le niveau d&apos;étude.
        /// </summary>
        public static string degreeID_error_message {
            get {
                return ResourceManager.GetString("degreeID_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niv étude.
        /// </summary>
        public static string degreeID_label {
            get {
                return ResourceManager.GetString("degreeID_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Permis .
        /// </summary>
        public static string drivingLicence_label {
            get {
                return ResourceManager.GetString("drivingLicence_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir l&apos;année d&apos;obtention de votre diplôme.
        /// </summary>
        public static string educationCompletionDate_error_message {
            get {
                return ResourceManager.GetString("educationCompletionDate_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anneé diplôme.
        /// </summary>
        public static string educationCompletionDate_label {
            get {
                return ResourceManager.GetString("educationCompletionDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desc. diplôme.
        /// </summary>
        public static string educationDescription_label {
            get {
                return ResourceManager.GetString("educationDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse email obligatoire.
        /// </summary>
        public static string email_address_error_message {
            get {
                return ResourceManager.GetString("email_address_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format email incorrect.
        /// </summary>
        public static string email_address_format_error_message {
            get {
                return ResourceManager.GetString("email_address_format_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string email_address_label {
            get {
                return ResourceManager.GetString("email_address_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format email incorrect.
        /// </summary>
        public static string email_format_error_message {
            get {
                return ResourceManager.GetString("email_format_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet obligatoire.
        /// </summary>
        public static string email_object_error_message {
            get {
                return ResourceManager.GetString("email_object_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objet.
        /// </summary>
        public static string email_object_label {
            get {
                return ResourceManager.GetString("email_object_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet obligatoire.
        /// </summary>
        public static string email_subject_error_message {
            get {
                return ResourceManager.GetString("email_subject_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sujet.
        /// </summary>
        public static string email_subject_label {
            get {
                return ResourceManager.GetString("email_subject_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre emplyés.
        /// </summary>
        public static string employee_label {
            get {
                return ResourceManager.GetString("employee_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le profil souhaité.
        /// </summary>
        public static string employmentStatut_error_message {
            get {
                return ResourceManager.GetString("employmentStatut_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profil souhaité.
        /// </summary>
        public static string employmentStatut_label {
            get {
                return ResourceManager.GetString("employmentStatut_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type contrat obligatoire.
        /// </summary>
        public static string employmentType_error_message {
            get {
                return ResourceManager.GetString("employmentType_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type contrat.
        /// </summary>
        public static string employmentType_label {
            get {
                return ResourceManager.GetString("employmentType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type contrat.
        /// </summary>
        public static string empTypeCandAlert_label {
            get {
                return ResourceManager.GetString("empTypeCandAlert_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de fin obligatoire.
        /// </summary>
        public static string endDateExp_error_message {
            get {
                return ResourceManager.GetString("endDateExp_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date fin.
        /// </summary>
        public static string endDateExp_label {
            get {
                return ResourceManager.GetString("endDateExp_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erruer s&apos;est produite dans le traitement de votre requête.
        /// </summary>
        public static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cadre.
        /// </summary>
        public static string executive_label {
            get {
                return ResourceManager.GetString("executive_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fax.
        /// </summary>
        public static string fax_label {
            get {
                return ResourceManager.GetString("fax_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom obligatoire.
        /// </summary>
        public static string firstname_error_message {
            get {
                return ResourceManager.GetString("firstname_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        public static string firstname_label {
            get {
                return ResourceManager.GetString("firstname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette information est obligatoire..
        /// </summary>
        public static string gbobal_error_message {
            get {
                return ResourceManager.GetString("gbobal_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant obligatoire.
        /// </summary>
        public static string identifier_error_message {
            get {
                return ResourceManager.GetString("identifier_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant.
        /// </summary>
        public static string identifier_label {
            get {
                return ResourceManager.GetString("identifier_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir l&apos;etablissement.
        /// </summary>
        public static string institution_error_message {
            get {
                return ResourceManager.GetString("institution_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Etablismt.
        /// </summary>
        public static string institution_label {
            get {
                return ResourceManager.GetString("institution_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Approuvé?.
        /// </summary>
        public static string isapproved_label {
            get {
                return ResourceManager.GetString("isapproved_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Verrouillé?.
        /// </summary>
        public static string islockedout_label {
            get {
                return ResourceManager.GetString("islockedout_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Princial?.
        /// </summary>
        public static string isprincipal_label {
            get {
                return ResourceManager.GetString("isprincipal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Description&apos;.
        /// </summary>
        public static string itemDescription_error_message {
            get {
                return ResourceManager.GetString("itemDescription_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string itemDescription_label {
            get {
                return ResourceManager.GetString("itemDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Titre&apos;.
        /// </summary>
        public static string itemName_error_message {
            get {
                return ResourceManager.GetString("itemName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre.
        /// </summary>
        public static string itemName_label {
            get {
                return ResourceManager.GetString("itemName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description activité.
        /// </summary>
        public static string jobActivitydescription_label {
            get {
                return ResourceManager.GetString("jobActivitydescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Secteur activité&apos;.
        /// </summary>
        public static string jobCategory_error_message {
            get {
                return ResourceManager.GetString("jobCategory_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur d&apos;act..
        /// </summary>
        public static string jobCategory_label {
            get {
                return ResourceManager.GetString("jobCategory_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur d&apos;act..
        /// </summary>
        public static string jobCategoryCandAler_label {
            get {
                return ResourceManager.GetString("jobCategoryCandAler_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur d&apos;act..
        /// </summary>
        public static string jobCategoryCandAlert_label {
            get {
                return ResourceManager.GetString("jobCategoryCandAlert_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fédération.
        /// </summary>
        public static string jobCompany_holding_name_label {
            get {
                return ResourceManager.GetString("jobCompany_holding_name_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom Entreprise.
        /// </summary>
        public static string jobCompanyName_label {
            get {
                return ResourceManager.GetString("jobCompanyName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Description du poste&apos;.
        /// </summary>
        public static string jobDescription_error_message {
            get {
                return ResourceManager.GetString("jobDescription_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string jobDescription_label {
            get {
                return ResourceManager.GetString("jobDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publiée?.
        /// </summary>
        public static string jobDisplay_label {
            get {
                return ResourceManager.GetString("jobDisplay_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Durée.
        /// </summary>
        public static string jobDuration_label {
            get {
                return ResourceManager.GetString("jobDuration_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant.
        /// </summary>
        public static string jobIdentifier_label {
            get {
                return ResourceManager.GetString("jobIdentifier_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autres infos.
        /// </summary>
        public static string jobOfferNote_label {
            get {
                return ResourceManager.GetString("jobOfferNote_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Référence offre à rappeler.
        /// </summary>
        public static string jobOfferReference_label {
            get {
                return ResourceManager.GetString("jobOfferReference_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Département ou région.
        /// </summary>
        public static string jobPosition_label {
            get {
                return ResourceManager.GetString("jobPosition_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau profil.
        /// </summary>
        public static string jobSkillLevel_label {
            get {
                return ResourceManager.GetString("jobSkillLevel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début.
        /// </summary>
        public static string jobStartDate_label {
            get {
                return ResourceManager.GetString("jobStartDate_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Titre de l&apos;offre&apos;.
        /// </summary>
        public static string jobTitle_error_message {
            get {
                return ResourceManager.GetString("jobTitle_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre offre.
        /// </summary>
        public static string jobTitle_label {
            get {
                return ResourceManager.GetString("jobTitle_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lien web de l&apos;offre sur votre site.
        /// </summary>
        public static string jobWebLink_label {
            get {
                return ResourceManager.GetString("jobWebLink_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir les mots clésde votre recherche.
        /// </summary>
        public static string keywords_error_message {
            get {
                return ResourceManager.GetString("keywords_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mots clés.
        /// </summary>
        public static string keywords_label {
            get {
                return ResourceManager.GetString("keywords_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niv. maitrise.
        /// </summary>
        public static string LangSkillLevel_label {
            get {
                return ResourceManager.GetString("LangSkillLevel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez choisir votre langue.
        /// </summary>
        public static string language_error_message {
            get {
                return ResourceManager.GetString("language_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        public static string language_label {
            get {
                return ResourceManager.GetString("language_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisation.
        /// </summary>
        public static string LangUsed {
            get {
                return ResourceManager.GetString("LangUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nbre  an. util. .
        /// </summary>
        public static string langYearOfExp_label {
            get {
                return ResourceManager.GetString("langYearOfExp_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Veuillez saisir le nombre d&apos;années d&apos;utilisation.
        /// </summary>
        public static string LangYearOfExpID_error_message {
            get {
                return ResourceManager.GetString("LangYearOfExpID_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire.
        /// </summary>
        public static string lastname_error_message {
            get {
                return ResourceManager.GetString("lastname_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string lastname_label {
            get {
                return ResourceManager.GetString("lastname_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niv. langue.
        /// </summary>
        public static string levelLanguage_label {
            get {
                return ResourceManager.GetString("levelLanguage_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string locartionDescription_label {
            get {
                return ResourceManager.GetString("locartionDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone géo..
        /// </summary>
        public static string location_label {
            get {
                return ResourceManager.GetString("location_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Adresse&apos;.
        /// </summary>
        public static string LocationItem_error_message {
            get {
                return ResourceManager.GetString("LocationItem_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string LocationItem_label {
            get {
                return ResourceManager.GetString("LocationItem_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre obligatoire !.
        /// </summary>
        public static string loyalty_error_message {
            get {
                return ResourceManager.GetString("loyalty_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre coupon.
        /// </summary>
        public static string loyalty_label {
            get {
                return ResourceManager.GetString("loyalty_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description obligatoire !.
        /// </summary>
        public static string loyaltyDescription_error_messae {
            get {
                return ResourceManager.GetString("loyaltyDescription_error_messae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description coupon.
        /// </summary>
        public static string loyaltyDescription_label {
            get {
                return ResourceManager.GetString("loyaltyDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description pg points.
        /// </summary>
        public static string loyaltyDescriptionp_label {
            get {
                return ResourceManager.GetString("loyaltyDescriptionp_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre pg points.
        /// </summary>
        public static string loyaltyp_label {
            get {
                return ResourceManager.GetString("loyaltyp_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantité.
        /// </summary>
        public static string lpQuantity_label {
            get {
                return ResourceManager.GetString("lpQuantity_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Devise.
        /// </summary>
        public static string lVCurrency_label {
            get {
                return ResourceManager.GetString("lVCurrency_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réduction.
        /// </summary>
        public static string lVDiscount_label {
            get {
                return ResourceManager.GetString("lVDiscount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos réduction.
        /// </summary>
        public static string lVDiscountInfo_label {
            get {
                return ResourceManager.GetString("lVDiscountInfo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de réduction obligatoire..
        /// </summary>
        public static string lVDiscountType_error_message {
            get {
                return ResourceManager.GetString("lVDiscountType_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de réduction.
        /// </summary>
        public static string lVDiscountType_label {
            get {
                return ResourceManager.GetString("lVDiscountType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos cadeau.
        /// </summary>
        public static string lVGifInfo_label {
            get {
                return ResourceManager.GetString("lVGifInfo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez saisir montant.
        /// </summary>
        public static string lvGiftAmount_error_message {
            get {
                return ResourceManager.GetString("lvGiftAmount_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant cadeau.
        /// </summary>
        public static string lvGiftAmount_label {
            get {
                return ResourceManager.GetString("lvGiftAmount_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir le type de coupon.
        /// </summary>
        public static string lVType_error_message {
            get {
                return ResourceManager.GetString("lVType_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type coupon.
        /// </summary>
        public static string lVType_label {
            get {
                return ResourceManager.GetString("lVType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le diplôme.
        /// </summary>
        public static string major_error_message {
            get {
                return ResourceManager.GetString("major_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation.
        /// </summary>
        public static string major_label {
            get {
                return ResourceManager.GetString("major_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut marital.
        /// </summary>
        public static string maritalStatus_label {
            get {
                return ResourceManager.GetString("maritalStatus_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description du document.
        /// </summary>
        public static string Media_description_label {
            get {
                return ResourceManager.GetString("Media_description_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre du document.
        /// </summary>
        public static string Media_label {
            get {
                return ResourceManager.GetString("Media_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre du document obligatoire..
        /// </summary>
        public static string Media_title_error_message {
            get {
                return ResourceManager.GetString("Media_title_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message obligatoire.
        /// </summary>
        public static string message_error_message {
            get {
                return ResourceManager.GetString("message_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de message obligatoire.
        /// </summary>
        public static string message_error_message_type {
            get {
                return ResourceManager.GetString("message_error_message_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autres infos .
        /// </summary>
        public static string message_label {
            get {
                return ResourceManager.GetString("message_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de message.
        /// </summary>
        public static string message_type_label {
            get {
                return ResourceManager.GetString("message_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre message.
        /// </summary>
        public static string message0_label {
            get {
                return ResourceManager.GetString("message0_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mobile.
        /// </summary>
        public static string mobile_phone_label {
            get {
                return ResourceManager.GetString("mobile_phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motivation Obligatoire !.
        /// </summary>
        public static string motivation_error_message {
            get {
                return ResourceManager.GetString("motivation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motivation.
        /// </summary>
        public static string motivation_label {
            get {
                return ResourceManager.GetString("motivation_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lettre motiv en PJ.
        /// </summary>
        public static string motivationfile_label {
            get {
                return ResourceManager.GetString("motivationfile_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nationalité.
        /// </summary>
        public static string nationality_label {
            get {
                return ResourceManager.GetString("nationality_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Projet pro.
        /// </summary>
        public static string note_label {
            get {
                return ResourceManager.GetString("note_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponibilité Obligatoire !.
        /// </summary>
        public static string noticePeriode_error_message {
            get {
                return ResourceManager.GetString("noticePeriode_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponibilité.
        /// </summary>
        public static string noticePeriode_label {
            get {
                return ResourceManager.GetString("noticePeriode_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desc. poste.
        /// </summary>
        public static string objective_label {
            get {
                return ResourceManager.GetString("objective_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string options_label {
            get {
                return ResourceManager.GetString("options_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disponibilité.
        /// </summary>
        public static string otherDisponibility_label {
            get {
                return ResourceManager.GetString("otherDisponibility_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motivation.
        /// </summary>
        public static string otherMotivation_label {
            get {
                return ResourceManager.GetString("otherMotivation_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau exp..
        /// </summary>
        public static string otherskillLevel_label {
            get {
                return ResourceManager.GetString("otherskillLevel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe obligatoire.
        /// </summary>
        public static string password_error_message {
            get {
                return ResourceManager.GetString("password_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string password_label {
            get {
                return ResourceManager.GetString("password_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe doit contenir au moins  6 caract..
        /// </summary>
        public static string password_length_message {
            get {
                return ResourceManager.GetString("password_length_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        public static string phone_label {
            get {
                return ResourceManager.GetString("phone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom boutique.
        /// </summary>
        public static string pointofSaleName_label {
            get {
                return ResourceManager.GetString("pointofSaleName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activité.
        /// </summary>
        public static string posActivity_code_label {
            get {
                return ResourceManager.GetString("posActivity_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description activité.
        /// </summary>
        public static string posActivitydescription_label {
            get {
                return ResourceManager.GetString("posActivitydescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Fonction&apos;.
        /// </summary>
        public static string position_error_message {
            get {
                return ResourceManager.GetString("position_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rôle de l&apos;entreprise.
        /// </summary>
        public static string position_label {
            get {
                return ResourceManager.GetString("position_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poste recherché obligatoire.
        /// </summary>
        public static string positionSought_error_message {
            get {
                return ResourceManager.GetString("positionSought_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poste rech..
        /// </summary>
        public static string positionSought_label {
            get {
                return ResourceManager.GetString("positionSought_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adresse.
        /// </summary>
        public static string posLocation_label {
            get {
                return ResourceManager.GetString("posLocation_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre logo.
        /// </summary>
        public static string PosLogo_label {
            get {
                return ResourceManager.GetString("PosLogo_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir votre expérience.
        /// </summary>
        public static string proExperience_error_message {
            get {
                return ResourceManager.GetString("proExperience_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expérience.
        /// </summary>
        public static string proExperience_label {
            get {
                return ResourceManager.GetString("proExperience_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir la description de votre expérience.
        /// </summary>
        public static string proExperienceDes_error_message {
            get {
                return ResourceManager.GetString("proExperienceDes_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description exp..
        /// </summary>
        public static string proExperienceDes_label {
            get {
                return ResourceManager.GetString("proExperienceDes_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avis obligatoire.
        /// </summary>
        public static string rating_error_message {
            get {
                return ResourceManager.GetString("rating_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avis.
        /// </summary>
        public static string rating_label {
            get {
                return ResourceManager.GetString("rating_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email obligatoire .
        /// </summary>
        public static string ratingAuthorEmail_error_message {
            get {
                return ResourceManager.GetString("ratingAuthorEmail_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string ratingAuthorEmail_label {
            get {
                return ResourceManager.GetString("ratingAuthorEmail_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom obligatoire .
        /// </summary>
        public static string ratingAuthorName_error_message {
            get {
                return ResourceManager.GetString("ratingAuthorName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        public static string ratingAuthorName_label {
            get {
                return ResourceManager.GetString("ratingAuthorName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avis.
        /// </summary>
        public static string ratingReviewContent {
            get {
                return ResourceManager.GetString("ratingReviewContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avis obligatoire .
        /// </summary>
        public static string ratingReviewContent_error_message {
            get {
                return ResourceManager.GetString("ratingReviewContent_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reponse.
        /// </summary>
        public static string ratingReviewResponse {
            get {
                return ResourceManager.GetString("ratingReviewResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reponse  obligatoire !.
        /// </summary>
        public static string ratingReviewResponse_error_message {
            get {
                return ResourceManager.GetString("ratingReviewResponse_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant obligatoire.
        /// </summary>
        public static string registernumer_error_message {
            get {
                return ResourceManager.GetString("registernumer_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant (Entreprise).
        /// </summary>
        public static string registernumer_label {
            get {
                return ResourceManager.GetString("registernumer_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rémunération.
        /// </summary>
        public static string salary_label {
            get {
                return ResourceManager.GetString("salary_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compl. rénumération.
        /// </summary>
        public static string salaryDescription_label {
            get {
                return ResourceManager.GetString("salaryDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur obligatoire.
        /// </summary>
        public static string sector_code_error_message {
            get {
                return ResourceManager.GetString("sector_code_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteur.
        /// </summary>
        public static string sector_code_label {
            get {
                return ResourceManager.GetString("sector_code_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner pays.
        /// </summary>
        public static string select_country_msg {
            get {
                return ResourceManager.GetString("select_country_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir &apos;Profil souhaité&apos;.
        /// </summary>
        public static string skill_error_message {
            get {
                return ResourceManager.GetString("skill_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profil souhaité.
        /// </summary>
        public static string skill_label {
            get {
                return ResourceManager.GetString("skill_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le domaine d&apos;expérience.
        /// </summary>
        public static string skillDescription_error_message {
            get {
                return ResourceManager.GetString("skillDescription_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Domaine exp. .
        /// </summary>
        public static string skillDescription_label {
            get {
                return ResourceManager.GetString("skillDescription_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernière utilisation diplôme obligatoire..
        /// </summary>
        public static string skillLastUsed_error_message {
            get {
                return ResourceManager.GetString("skillLastUsed_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernière utilisation..
        /// </summary>
        public static string skillLastUsed_label {
            get {
                return ResourceManager.GetString("skillLastUsed_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau expérience obligatoire.
        /// </summary>
        public static string skillLevel_error_message {
            get {
                return ResourceManager.GetString("skillLevel_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau exp..
        /// </summary>
        public static string skillLevel_label {
            get {
                return ResourceManager.GetString("skillLevel_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau exp..
        /// </summary>
        public static string skillLevelCandAlert_label {
            get {
                return ResourceManager.GetString("skillLevelCandAlert_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez saisir le nombre d&apos;années d&apos;expériences.
        /// </summary>
        public static string skillYearOfExp_error_message {
            get {
                return ResourceManager.GetString("skillYearOfExp_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Années expériences.
        /// </summary>
        public static string skillYearOfExp_label {
            get {
                return ResourceManager.GetString("skillYearOfExp_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date de début obligatoire.
        /// </summary>
        public static string startDateExp_error_message {
            get {
                return ResourceManager.GetString("startDateExp_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début.
        /// </summary>
        public static string startDateExp_label {
            get {
                return ResourceManager.GetString("startDateExp_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activé.
        /// </summary>
        public static string Status_label {
            get {
                return ResourceManager.GetString("Status_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous Catégorie Obligatoire !.
        /// </summary>
        public static string SubCatalogName_error_message {
            get {
                return ResourceManager.GetString("SubCatalogName_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sous Catégorie.
        /// </summary>
        public static string SubCatalogName_label {
            get {
                return ResourceManager.GetString("SubCatalogName_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tél mobile.
        /// </summary>
        public static string Telphone_label {
            get {
                return ResourceManager.GetString("Telphone_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Civilité obligatoire.
        /// </summary>
        public static string title_error_message {
            get {
                return ResourceManager.GetString("title_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Civilité.
        /// </summary>
        public static string title_label {
            get {
                return ResourceManager.GetString("title_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez choisir &apos;Ville&apos;.
        /// </summary>
        public static string town_error_message {
            get {
                return ResourceManager.GetString("town_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        public static string town_label {
            get {
                return ResourceManager.GetString("town_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rég.,Départ.,Cp obligatoire..
        /// </summary>
        public static string TownLocation_error_message {
            get {
                return ResourceManager.GetString("TownLocation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rég.,Départ.,Cp..
        /// </summary>
        public static string TownLocation_label {
            get {
                return ResourceManager.GetString("TownLocation_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ! Veuillez attacher votre &apos;CV&apos;.
        /// </summary>
        public static string uploadfile_error_message {
            get {
                return ResourceManager.GetString("uploadfile_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite au cours de l&apos;activation de votre compte.&lt;br&gt;&lt;br&gt;Veuillez contacter TAMZAG pour plus d&apos;information..
        /// </summary>
        public static string user_activation_error_message {
            get {
                return ResourceManager.GetString("user_activation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre destinataire.
        /// </summary>
        public static string web_contact_filter_label {
            get {
                return ResourceManager.GetString("web_contact_filter_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site web  obligatoire.
        /// </summary>
        public static string web_site_error_message {
            get {
                return ResourceManager.GetString("web_site_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site web.
        /// </summary>
        public static string web_site_label {
            get {
                return ResourceManager.GetString("web_site_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Format site web incorrect.
        /// </summary>
        public static string website_format_error_message {
            get {
                return ResourceManager.GetString("website_format_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année expériences.
        /// </summary>
        public static string yearOfExperience_label {
            get {
                return ResourceManager.GetString("yearOfExperience_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le lien Youtube est incorrect.
        /// </summary>
        public static string YoutubeUrlValidate {
            get {
                return ResourceManager.GetString("YoutubeUrlValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone géographique.
        /// </summary>
        public static string zone_geo_label {
            get {
                return ResourceManager.GetString("zone_geo_label", resourceCulture);
            }
        }
    }
}
